import {
    Mail,
    Phone,
    MapPin,
    Linkedin,
    Github,
    Twitter,
    Instagram,
    Facebook,
} from "lucide-react";

// Static data
export const aboutData = {
  personalInfo: {
    name: "Abu Saiyed Joy",
    title: "Full Stack Developer",
    bio: "Passionate full-stack developer with expertise in building modern, scalable web applications. I specialize in React, Next.js, and Node.js, leveraging TypeScript to create type-safe, maintainable code. My tech stack includes Prisma ORM and PostgreSQL for robust database solutions. I focus on crafting user-centric applications with clean code architecture and exceptional user experiences. Driven by continuous learning and innovation, I transform ideas into high-quality digital products that make an impact.",
    location: "Foy's Lake, Chattogram",
    email: "abusaiyedjoy1@email.com",
    phone: "+8801988084185",
    availability: "Available for new projects",
  },
  education: [
    {
      degree: "Diploma in Computer Science & Technologies",
      institution: "Chattogram Polytechnic Institute",
      year: "2023 - present",
      gpa: "3.30/4.00",
      achievements: ["Science Club President", "Best Final Year Project Award"],
    },
    {
      degree: "Higher Secondary Certificate",
      institution: "Cumilla Govt. College",
      year: "2022 - 2024",
      gpa: "5.00/5.00",
      achievements: ["Board Scholarship", "Science Club President"],
    },
  ],
  skills: {
    frontend: [
      { name: "React", level: 95, years: 3 },
      { name: "Next.js", level: 90, years: 2 },
      { name: "TypeScript", level: 88, years: 2.5 },
      { name: "Tailwind CSS", level: 92, years: 2 },
    ],
    backend: [
      { name: "Node.js", level: 90, years: 3 },
      { name: "Express.js", level: 88, years: 2.5 },
      { name: "GraphQL", level: 78, years: 1.5 },
      { name: "REST APIs", level: 92, years: 3 },
    ],
    database: [
      { name: "MongoDB", level: 85, years: 2.5 },
      { name: "Mongoose", level: 75, years: 1.5 },
      { name: "PostgreSQL", level: 80, years: 2 },
      { name: "Prisma", level: 82, years: 1 },
    ],
    tools: [
      { name: "Git", level: 90, years: 3 },
      { name: "Docker", level: 78, years: 1.5 },
      { name: "AWS", level: 75, years: 2 },
      { name: "Vercel", level: 88, years: 2 },
    ],
  },
  socialLinks: {
    github: "https://github.com/abusaiyedjoy",
    linkedin: "https://linkedin.com/in/abusaiyedjoy",
    twitter: "https://twitter.com/abusaiyedjoy",
  },
};

// Blog data
export const blogsData = [
  {
    id: 1,
    title: "Building Scalable React Applications with Next.js 14",
    excerpt: "Discover the latest features in Next.js 14 and learn how to build performant, scalable applications with server components and app router.",
    content: "Full blog content here...",
    image: "/blog1.jpg",
    category: "Web Development",
    tags: ["React", "Next.js", "JavaScript", "Performance"],
    author: "Abu Saiyed Joy",
    authorAvatar: "/profile.jpg",
    date: "2024-09-15",
    readTime: "8 min read",
    views: 1254,
    likes: 89,
    comments: 23,
  },
  {
    id: 2,
    title: "Mastering TypeScript: Advanced Types and Patterns",
    excerpt: "Deep dive into TypeScript's advanced type system, exploring utility types, conditional types, and real-world design patterns.",
    content: "Full blog content here...",
    image: "/blog2.jpg",
    category: "Programming",
    tags: ["TypeScript", "JavaScript", "Programming"],
    author: "Abu Saiyed Joy",
    authorAvatar: "/profile.jpg",
    date: "2024-09-10",
    readTime: "12 min read",
    views: 2103,
    likes: 156,
    comments: 45,
    
  },
  {
    id: 3,
    title: "State Management in React: Redux vs Zustand",
    excerpt: "A comprehensive comparison of popular state management solutions, helping you choose the right tool for your React application.",
    content: "Full blog content here...",
    image: "/blog3.jpg",
    category: "Web Development",
    tags: ["React", "State Management", "Redux", "Zustand"],
    author: "Abu Saiyed Joy",
    authorAvatar: "/profile.jpg",
    date: "2024-09-05",
    readTime: "10 min read",
    views: 1876,
    likes: 134,
    comments: 38,
    
  },
  {
    id: 4,
    title: "CSS Grid vs Flexbox: When to Use What",
    excerpt: "Understanding the differences between CSS Grid and Flexbox, and when to use each layout system for optimal results.",
    content: "Full blog content here...",
    image: "/blog4.jpg",
    category: "CSS & Design",
    tags: ["CSS", "Web Design", "Frontend"],
    author: "Abu Saiyed Joy",
    authorAvatar: "/profile.jpg",
    date: "2024-08-28",
    readTime: "6 min read",
    views: 945,
    likes: 67,
    comments: 15,
  },
  {
    id: 5,
    title: "Building RESTful APIs with Node.js and Express",
    excerpt: "Learn how to design and build robust RESTful APIs using Node.js, Express, and best practices for API development.",
    content: "Full blog content here...",
    image: "/blog5.jpg",
    category: "Backend",
    tags: ["Node.js", "Express", "API", "Backend"],
    author: "Abu Saiyed Joy",
    authorAvatar: "/profile.jpg",
    date: "2024-08-20",
    readTime: "15 min read",
    views: 1567,
    likes: 98,
    comments: 29,
  },
  {
    id: 7,
    title: "Optimizing Web Performance: Core Web Vitals",
    excerpt: "Master the art of web performance optimization by understanding and improving Core Web Vitals metrics.",
    content: "Full blog content here...",
    image: "/blog7.jpg",
    category: "Performance",
    tags: ["Performance", "Web Vitals", "Optimization"],
    author: "Abu Saiyed Joy",
    authorAvatar: "/profile.jpg",
    date: "2024-08-10",
    readTime: "9 min read",
    views: 1678,
    likes: 112,
    comments: 34,
  },
  {
    id: 8,
    title: "Authentication in Next.js with NextAuth.js",
    excerpt: "Implement secure authentication in your Next.js applications using NextAuth.js with various providers.",
    content: "Full blog content here...",
    image: "/blog8.jpg",
    category: "Security",
    tags: ["Authentication", "Next.js", "Security"],
    author: "Abu Saiyed Joy",
    authorAvatar: "/profile.jpg",
    date: "2024-08-05",
    readTime: "13 min read",
    views: 2045,
    likes: 145,
    comments: 41,
  },
  {
    id: 9,
    title: "GraphQL vs REST: Choosing the Right API",
    excerpt: "Compare GraphQL and REST APIs, their pros and cons, and how to decide which one fits your project needs.",
    content: "Full blog content here...",
    image: "/blog9.jpg",
    category: "API Design",
    tags: ["GraphQL", "REST", "API"],
    author: "Abu Saiyed Joy",
    authorAvatar: "/profile.jpg",
    date: "2024-07-30",
    readTime: "10 min read",
    views: 1432,
    likes: 93,
    comments: 27,
  },
];

// Project data
export const projectsData = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description: "A full-stack e-commerce solution with payment integration, real-time inventory management, and admin dashboard. Built with modern tech stack for optimal performance.",
    image: "./project1.jpg",
    category: "Full Stack",
    tags: ["React", "Node.js", "MongoDB", "Stripe"],
    github: "https://github.com/abusaiyedjoy/ecommerce",
    live: "https://ecommerce-demo.vercel.app"
    },
  {
    id: 2,
    title: "Task Management App",
    description: "Collaborative task management application with real-time updates, team collaboration features, and intuitive drag-and-drop interface.",
    image: "./project2.jpg",
    category: "Frontend",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase"],
    github: "https://github.com/abusaiyedjoy/task-manager",
    live: "https://taskmanager-demo.vercel.app",
    stars: 189,
    forks: 43,
    date: "2024",
    featured: true,
  },
  {
    id: 3,
    title: "AI Content Generator",
    description: "AI-powered content generation tool using OpenAI API. Generate blogs, social media posts, and marketing copy with advanced customization options.",
    image: "./project3.jpg",
    category: "Full Stack",
    tags: ["Next.js", "OpenAI", "PostgreSQL", "Prisma"],
    github: "https://github.com/abusaiyedjoy/ai-content",
    live: "https://ai-content-demo.vercel.app",
    stars: 312,
    forks: 89,
    date: "2023",
    featured: true,
  },
  {
    id: 4,
    title: "Weather Dashboard",
    description: "Modern weather dashboard with beautiful visualizations, location-based forecasts, and historical weather data analysis.",
    image: "./project4.jpg",
    category: "Frontend",
    tags: ["React", "Chart.js", "Weather API", "Tailwind"],
    github: "https://github.com/abusaiyedjoy/weather-dashboard",
    live: "https://weather-demo.vercel.app",
    stars: 156,
    forks: 34,
    date: "2023",
    featured: false,
  },
  {
    id: 5,
    title: "Social Media Analytics",
    description: "Comprehensive social media analytics platform with real-time data tracking, engagement metrics, and detailed reporting features.",
    image: "./project5.jpg",
    category: "Full Stack",
    tags: ["React", "Express", "MongoDB", "Redis"],
    github: "https://github.com/abusaiyedjoy/social-analytics",
    live: "https://analytics-demo.vercel.app",
    stars: 203,
    forks: 56,
    date: "2023",
    featured: false,
  },
  {
    id: 6,
    title: "Portfolio Builder",
    description: "No-code portfolio builder with drag-and-drop interface, multiple themes, and one-click deployment to custom domains.",
    image: "./project6.jpg",
    category: "Full Stack",
    tags: ["Next.js", "Tailwind", "PostgreSQL", "AWS"],
    github: "https://github.com/abusaiyedjoy/portfolio-builder",
    live: "https://portfolio-builder-demo.vercel.app",
    stars: 278,
    forks: 71,
    date: "2024",
    featured: false,
  },
];

export const technologies = [
    {
      name: "HTML",
      color: "bg-blue-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg",
    },
    {
      name: "CSS",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg",
    },
    {
      name: "Java Script",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg",
    },
    {
      name: "React",
      color: "bg-blue-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg",
    },
    {
      name: "Vite",
      color: "bg-blue-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vite/vite-original.svg",
    },
    {
      name: "Type Script",
      color: "bg-blue-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg",
    },
    {
      name: "Tailwind CSS",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg",
    },
    {
      name: "Node.js",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg",
    },
    {
      name: "GraphQL",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/graphql/graphql-plain.svg",
    },
    {
      name: "Express JS",
      color: "bg-blue-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg",
    },
    {
      name: "Mongo DB",
      color: "bg-blue-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongodb/mongodb-original.svg",
    },
    {
      name: "Mongoose",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongoose/mongoose-original.svg",
    },
    {
      name: "Prisma",
      color: "bg-blue-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/prisma/prisma-original.svg",
    },
    {
      name: "PostgreSQL",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original.svg",
    },
    {
      name: "Docker",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-original.svg",
    },
    {
      name: "AWS",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/amazonwebservices/amazonwebservices-original-wordmark.svg",
    },
    {
      name: "Figma",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg",
    },
    {
      name: "Git",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg",
    },
    {
      name: "Github",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg",
    },
    {
      name: "Vercel",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vercel/vercel-original.svg",
    },
    {
      name: "Railway",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/railway/railway-original.svg",
    },
    {
      name: "Nelify",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/netlify/netlify-original.svg",
    },
    {
      name: "VS Code",
      color: "bg-green-600",
      src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vscode/vscode-original.svg",
    },
    
  ];
  
  // Contact information
 export const contactInfo = {
    email: "abusaiyedjoy1@email.com",
    phone: "+8801988084185",
    location: "Foy's Lake, Chattogram, Bangladesh",
    timezone: "GMT+6 (Bangladesh Time)",
    availability: "Monday - Friday, 9:00 AM - 6:00 PM",
    responseTime: "Within 24 hours",
  };
  
 export const socialLinks = [
    {
      name: "LinkedIn",
      icon: Linkedin,
      url: "https://linkedin.com/in/abusaiyedjoy",
      color: "from-blue-600 to-blue-700",
      hoverColor: "hover:shadow-blue-500/50",
    },
    {
      name: "GitHub",
      icon: Github,
      url: "https://github.com/abusaiyedjoy",
      color: "from-gray-800 to-gray-900",
      hoverColor: "hover:shadow-gray-500/50",
    },
    {
      name: "Twitter",
      icon: Twitter,
      url: "https://twitter.com/abusaiyedjoy",
      color: "from-sky-400 to-sky-600",
      hoverColor: "hover:shadow-sky-500/50",
    },
    {
      name: "Instagram",
      icon: Instagram,
      url: "https://instagram.com/abusaiyedjoy",
      color: "from-pink-500 to-purple-600",
      hoverColor: "hover:shadow-pink-500/50",
    },
    {
      name: "Facebook",
      icon: Facebook,
      url: "https://www.facebook.com/abu.saiyed.joy.2024",
      color: "from-blue-500 to-blue-700",
      hoverColor: "hover:shadow-blue-600/50",
    },
  ];
  
 export const quickContacts = [
    {
      icon: Mail,
      title: "Email Me",
      value: contactInfo.email,
      description: "Drop me an email anytime",
      link: `mailto:${contactInfo.email}`,
      gradient: "from-[#334CEC] to-blue-600",
    },
    {
      icon: Phone,
      title: "Call Me",
      value: contactInfo.phone,
      description: "Mon-Fri from 9am to 6pm",
      link: `tel:${contactInfo.phone}`,
      gradient: "from-green-500 to-emerald-600",
    },
    {
      icon: MapPin,
      title: "Visit Me",
      value: contactInfo.location,
      description: "Available for meetings",
      link: "#",
      gradient: "from-purple-500 to-pink-600",
    },
  ];
  